version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    env_file: ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/generated:/app/generated
  web:
    build: ./web
    ports:
      - "5173:5173"
